### ISSUE TITLE
Renaming batches of results

### ISSUE THREAD

**Issue by DavidHuji** [Samsung/qaboard#3]
First, thanks for open-source this great project.
I would like to suggest a useful feature that will enable to edit batch names (really useful when you have many batches and you want to rename them to be with a meaningful concise names).

**Comment by arthur-flam** [comment]
Hi David,
It is a very good idea, likely useful to many users.
Since it's a small feature, I expect to have something to show you by next week.


I'll add a `change label` menu item before the `redo`:
![image](https://user-images.githubusercontent.com/2649055/76434343-3a396f00-63be-11ea-9fb1-a4c4f1e51073.png)

**Comment by arthur-flam** [comment]
Hi David,
I added the feature, and will push/deploy it very soon 👍 
Arthur

**Comment by arthur-flam** [comment]
This is what is looks like:
![rename-batch](https://user-images.githubusercontent.com/2649055/76699996-913f8c80-66bb-11ea-9959-9d5597529d99.gif)

**Comment by DavidHuji** [comment]
Looks great, many thanks!
